### ISSUE TITLE
Update to support MultiProcess?

### ISSUE THREAD

**Issue by omperus** [ashphy/toggle-find-bar#1]
Hello, i really like your addon but currently its not compatible with the new firefox multiprocess, do you think its possible to update it? Thanks.

**Comment by ashphy** [comment]
Sorry this extension uses XUL which will obsolete.
Because it is hard to adopt Webextension, there is no plan to update.

**Comment by omperus** [comment]
And no plan to create another similar extension? 😢

**Comment by ashphy** [comment]
It is impossible.
